/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./Views/**/*.cshtml", "./Areas/**/*.cshtml"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "accent-electric-blue": "#00E0FF",
        "secondary-fixed": "#a5eeff",
        "accent-cyber-lime": "#CCFF00",
        "tertiary-fixed-dim": "#b6c9d8",
        "on-tertiary-fixed": "#0b1d29",
        "tertiary-fixed": "#d2e5f5",
        "surface-container-highest": "#333627",
        "surface": "#111508",
        "on-secondary": "#00363f",
        "surface-container": "#1e2113",
        "primary-container": "#c3f400",
        "on-primary-fixed-variant": "#3c4d00",
        "on-tertiary": "#21323e",
        "background": "#111508",
        "inverse-surface": "#e2e4cf",
        "surface-container-lowest": "#0c0f04",
        "on-secondary-fixed-variant": "#004e5a",
        "tertiary-container": "#d2e5f5",
        "on-secondary-fixed": "#001f25",
        "surface-dim": "#111508",
        "bg-surface-depth-3": "#252525",
        "tertiary": "#ffffff",
        "surface-bright": "#373b2c",
        "surface-container-low": "#1a1d10",
        "error-container": "#93000a",
        "on-primary-fixed": "#161e00",
        "inverse-on-surface": "#2f3223",
        "primary-fixed-dim": "#abd600",
        "on-primary-container": "#556d00",
        "text-secondary": "#B3B3B3",
        "on-background": "#e2e4cf",
        "on-tertiary-fixed-variant": "#374956",
        "on-error": "#690005",
        "on-primary": "#283500",
        "secondary-fixed-dim": "#00daf8",
        "primary-fixed": "#c3f400",
        "on-tertiary-container": "#556774",
        "surface-tint": "#abd600",
        "secondary": "#b9f1ff",
        "accent-vivid-orange": "#FF5C00",
        "on-surface": "#e2e4cf",
        "surface-container-high": "#282b1d",
        "bg-surface-depth-2": "#1A1A1A",
        "on-surface-variant": "#c4c9ac",
        "on-secondary-container": "#005f6d",
        "surface-variant": "#333627",
        "outline": "#8e9379",
        "inverse-primary": "#506600",
        "bg-surface-depth-1": "#0D0D0D",
        "on-error-container": "#ffdad6",
        "outline-variant": "#444933",
        "primary": "#ffffff",
        "bg-pure": "#000000",
        "secondary-container": "#00e0ff",
        "text-primary": "#FFFFFF",
        "error": "#ffb4ab"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        lg: "48px",
        sm: "12px",
        base: "8px",
        gutter: "24px",
        xl: "80px",
        md: "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-hero": ["Space Grotesk"],
        "price-display": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["Space Grotesk"],
        h3: ["Space Grotesk"],
        h2: ["Space Grotesk"],
        h1: ["Space Grotesk"]
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "price-display": ["20px", { lineHeight: "1", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        h2: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        h1: ["48px", { lineHeight: "1.2", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
